apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sshashwat
  namespace: default
spec:
  profile:
    displayName: Shashwat
  memberOf: [guests]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: curtain
  annotations:
    github.com: Wipro-Organization-105/first-strike
spec:
  type: service
  owner: guests
  lifecycle: experimental

