apiVersion: backstage.io/v1alpha1   #sample code
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
spec:
  type: container-image
  owner: user:guest
  lifecycle: experimental
