apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: dockerfile-template
  title: Create Workspace Image
  description: Workflow to create a workspace image which will be used in templates.
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Dockerfile Configuration
      required:
        - dockerfile
      oneOf:
        - title: Python
          properties:
            dockerfileType:
              const: python
            dockerfile:
              type: string
              title: Dockerfile
              ui:widget: textarea
              ui:options:
                rows: 22
              default: |
                FROM ubuntu:latest

                ENV DEBIAN_FRONTEND=noninteractive

                RUN apt-get update && apt-get install -y \
                    curl \
                    wget \
                    git \
                    python3 \
                    python3-pip \
                    sudo \
                    ca-certificates \
                    gnupg \
                    && rm -rf /var/lib/apt/lists/*


                COPY install-vscode-extentions.sh /usr/local/bin/install-vscode-extentions.sh
                RUN chmod +x /usr/local/bin/install-vscode-extentions.sh

                RUN useradd -m wcd && \
                echo "wcd ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

                USER wcd
                WORKDIR /home/wcd
        - title: Yocto
          properties:
            dockerfileType:
              const: yocto
            dockerfile:
              type: string
              title: Dockerfile
              ui:widget: textarea
              ui:options:
                rows: 22
              default: |
                FROM yoctolinux:2.11
    - title: Fill in some steps
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Name of the Dev Container
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description of Dev Container
          type: string
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
 
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    #- id: fetch-base
    #  name: Fetch Base
    #  action: fetch:template
    #  input:
    #    url: ./content
    #    values:
    #      baseImage: ${{ parameters.baseImage }}
    #      dockerfileRunCommands: ${{ parameters.dockerfileRunCommands }}
    #      name: ${{ parameters.name }}
    #      description: ${{ parameters.description }}

    # This step publishes the contents of the working directory to GitHub.
    # If you or your organization prefer another default branch name over 'main'
    # you can change that here.
    
    - id: write-dockerfile
      name: Dockerfile
      action: fs:write
      input:
        path: Dockerfile
        content: ${{ parameters.dockerfile }}


    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    # Let's notify the user that the template has completed using the Notification action
    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:default/guest
        title: 'Template executed'
        info: 'Your template has been executed'
        severity: 'normal'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
